.Dd April 12, 2020
.Dt HTPING 1
.Os
.Sh NAME
.Nm htping
.Nd periodically send HTTP requests
.Sh SYNOPSIS
.Nm
.Op Fl 4
.Op Fl 6
.Op Fl H Ar "field:value"
.Op Fl X Ar "method"
.Op Fl c Ar count
.Op Fl i Ar interval
.Op Fl f
.Op Fl k
.Op Fl -http1.1
.Op Fl -keepalive
.Op Fl l Ar addr
.Op Fl q
.Ar urls ...
.Sh DESCRIPTION
The
.Nm
utility periodically sends HTTP requests to
.Ar urls ,
prints the results and computes some statistics at exit.
Use Ctrl-C to quit
.Nm .
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl 4
Use IPv4 only.
.It Fl 6
Use IPv6 only.
.It Fl H Ar "field:value"
Add an additional HTTP header to the requests.
.It Fl X Ar method
Send a different HTTP
.Ar method
than the default
.Ql HEAD .
.It Fl c Ar count
Stop after sending
.Ar count
requests.
By default,
.Nm
loops indefinitely.
.It Fl i Ar interval
Perform one HTTP request every
.Ar interval
.Pq default: Sq 1s .
.It Fl f
Flood mode: perform requests back-to-back without waiting.
.It Fl k
Turn TLS verification errors into warnings.
.It Fl -http1.1
Disable HTTP/2 requests.
.It Fl -keepalive
Enable keepalive resp.\& use persistent connections.
.It Fl l Ar addr
Start a HTTP server at
.Ar addr
(e.g.\&
.Sq :9100 )
to provide Prometheus metrics at
.Sq /metrics .
.It Fl q
Quiet mode, don't print request status lines.
.El
.Sh EXIT STATUS
.Ex -std
.Sh EXAMPLES
Example output:
.Bd -literal -offset indent
HEAD http://example.com
0 bytes from 93.184.216.34:80: HTTP/1.1 200 seq=0 time=0.211 ms
0 bytes from 93.184.216.34:80: HTTP/1.1 200 seq=1 time=0.222 ms
0 bytes from 93.184.216.34:80: HTTP/1.1 200 seq=2 time=0.221 ms
0 bytes from 93.184.216.34:80: HTTP/1.1 200 seq=3 time=0.222 ms
^C
4 requests sent, 4 responses, 100% successful, time 4000ms
rtt min/avg/max/mdev = 0.211/0.219/0.222/0.005 ms
.Ed
.Sh SEE ALSO
.Xr curl 1 ,
.Xr httping 1
.Sh AUTHORS
.An Leah Neukirchen Aq Mt leah@vuxu.org
.Sh LICENSE
.Nm
is in the public domain.
.Pp
To the extent possible under law,
the creator of this work
has waived all copyright and related or
neighboring rights to this work.
.Pp
.Lk http://creativecommons.org/publicdomain/zero/1.0/
